CREATE TABLE IF NOT EXISTS PRICES (
    PRICE_ID BIGINT NOT NULL,
    BRAND_ID BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    START_DATE TIMESTAMP NOT NULL,
    END_DATE TIMESTAMP,
    PRIORITY INTEGER NOT NULL,
    PRICE DECIMAL(10, 2) NOT NULL,
    CURRENCY VARCHAR(3) NOT NULL,
    PRIMARY KEY (PRICE_ID)
);

CREATE INDEX IF NOT EXISTS IDX_PRICES_BRAND_PRODUCT_DATES
    ON PRICES (BRAND_ID, PRODUCT_ID, START_DATE, END_DATE);